site_name: IAW

nav:
    - Principal: index.md
    - Practicas: practicas.md
    - Practica 01-04: practica-01-04.md
    - Acerca de: about.md

theme:
    name: material
    font: 
        text: Roboto Mono
    language: es
    icon:
        logo: material/library-outline
    features:
        - header.autohide

