site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Practicas: practicas.md
    - Practica 01-04: practica-01-04.md

theme:
    name: readthedocs
    font:
        text: roboto mono
    language: es
    icon:
        logo: material/library-outline
    features:
        - header.autohide

